### ISSUE TITLE
Incorrect resolution: 5.5-portrait-1080x1920(H.264).mov

### ISSUE THREAD

**Issue by alexacz** [12q/iOSPreviewsSamples#1]
Incorrect resolution : [5.5-portrait-1080x1920(H.264).mov](https://github.com/12q/iOSPreviewsSamples/blob/main/5.5-portrait-1080x1920(H.264).mov)

**Comment by 12q** [comment]
> Incorrect resolution : [5.5-portrait-1080x1920(H.264).mov](https://github.com/12q/iOSPreviewsSamples/blob/main/5.5-portrait-1080x1920(H.264).mov)

Thanks, I've fixed that. Check it out.

**Comment by alexacz** [comment]
not yet fixed

**Comment by 12q** [comment]
ur right, check it out now
